apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  labels:
    app: nexus
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - port: 8081        # service port in cluster
      targetPort: 8081  # container port in pod
      nodePort: 30081   # external port on Minikube node

